# Generated by Django 5.0.4 on 2024-04-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('patron', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=20)),
                ('regdate', models.DateField()),
                ('email', models.EmailField(max_length=20)),
                ('password', models.SlugField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
