# Generated by Django 5.0.4 on 2024-04-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0002_alter_user_email_alter_user_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='patron',
            new_name='patr',
        ),
    ]
