# Generated by Django 5.0.3 on 2024-05-16 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0006_room_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='photo',
            field=models.ImageField(default='static/images/номер.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
