# Generated by Django 5.0.6 on 2024-05-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0010_alter_review_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rate',
            new_name='rate_of',
        ),
    ]
