# Generated by Django 5.0.6 on 2024-05-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0012_alter_room_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-price']},
        ),
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.ImageField(upload_to='static/images/rooms'),
        ),
    ]
